# numpy.nonzero 

numpy.nonzero 是返回tuple，tuple的个数是根据numpy的维度来决定，比如，下面的是二维

In [4]:
import numpy as np
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

返回 (array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))， 表示4个非零元素，分别是(0,0)、(1,1)、(2,0)、(2,0)，如果是三维numpy，的nonzero方法得到的tuple的长度为3

# numpy.searchsorted

np.searchsorted(a,b),a是有序数组，返回b的每个元素向a里插入后的index

In [1]:
import numpy as np
a = np.array([1,3,5])
b=np.arange(0,7)
c=np.searchsorted(a,b)
print (c)

[0 0 1 1 2 2 3]


# numpy.nditer

由于numpy数组往往是多维的，因此遍历数组时，用while、for会比较费事，用numpy.nditer就解决了numpy数组遍历的问题

In [4]:
import numpy as np
a = np.arange(18).reshape(2, 3, 3)
print(a)
for i in np.nditer(a, order='C'):
    print(i,end=' ')
print('----')
for i in np.nditer(a, order='F'):
    print(i,end=' ')
print('----')
for i in np.nditer(a, order='K'):
    print(i,end=' ')

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 ----
0 9 3 12 6 15 1 10 4 13 7 16 2 11 5 14 8 17 ----
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 

In [5]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a.T):
    print (x, end=", " )
print ('\n')
for x in np.nditer(a):
    print (x, end=", " )
print ('\n')

0, 1, 2, 3, 4, 5, 

0, 1, 2, 3, 4, 5, 



上面遍历a和a.T都是输出一样

In [7]:
for x in np.nditer(a,order='F'):
    print (x, end=", " )
print ('\n')
for x in np.nditer(a.T,order='F'):
    print (x, end=", " )
print ('\n')

0, 3, 1, 4, 2, 5, 

0, 1, 2, 3, 4, 5, 



order='F'是按列优先

In [8]:
for x in np.nditer(a,order='C'):
    print (x, end=", " )
print ('\n')
for x in np.nditer(a.T,order='C'):
    print (x, end=", " )
print ('\n')

0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 



order='C'是按行优先

In [10]:
a = np.arange(10,22)
a = a.reshape(3,4)
print  ('第一个数组为：')
print (a)

print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)
print (b)

print ('修改后的数组为：')
for x,y in np.nditer([a,b]):
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
第二个数组为：
[1 2 3 4]
修改后的数组为：
10:1, 11:2, 12:3, 13:4, 14:1, 15:2, 16:3, 17:4, 18:1, 19:2, 20:3, 21:4, 

上面是广播迭代功能

In [15]:
a = np.arange(10,22)
a = a.reshape(3,4)
print  ('第一个数组为：')
print (a)

print ('第二个数组为：')
b = np.array([[1],  [2],  [3]], dtype =  int)
print (b)

print ('修改后的数组为：')
for x,y in np.nditer([a,b]):
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
第二个数组为：
[[1]
 [2]
 [3]]
修改后的数组为：
10:1, 11:1, 12:1, 13:1, 14:2, 15:2, 16:2, 17:2, 18:3, 19:3, 20:3, 21:3, 