# numpy.nonzero 

numpy.nonzero 是返回tuple，tuple的个数是根据numpy的维度来决定，比如，下面的是二维

In [2]:
import numpy as np
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
np.nonzero(x)

(array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))

返回 (array([0, 1, 2, 2], dtype=int64), array([0, 1, 0, 1], dtype=int64))， 表示4个非零元素，分别是(0,0)、(1,1)、(2,0)、(2,0)，如果是三维numpy，的nonzero方法得到的tuple的长度为3

# numpy.searchsorted

np.searchsorted(a,b),a是有序数组，返回b的每个元素向a里插入后的index

In [1]:
import numpy as np
a = np.array([1,3,5])
b=np.arange(0,7)
c=np.searchsorted(a,b)
print (c)

[0 0 1 1 2 2 3]


# numpy.nditer

由于numpy数组往往是多维的，因此遍历数组时，用while、for会比较费事，用numpy.nditer就解决了numpy数组遍历的问题

In [4]:
import numpy as np
a = np.arange(18).reshape(2, 3, 3)
print(a)
for i in np.nditer(a, order='C'):
    print(i,end=' ')
print('----')
for i in np.nditer(a, order='F'):
    print(i,end=' ')
print('----')
for i in np.nditer(a, order='K'):
    print(i,end=' ')

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 ----
0 9 3 12 6 15 1 10 4 13 7 16 2 11 5 14 8 17 ----
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 

In [5]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a.T):
    print (x, end=", " )
print ('\n')
for x in np.nditer(a):
    print (x, end=", " )
print ('\n')

0, 1, 2, 3, 4, 5, 

0, 1, 2, 3, 4, 5, 



上面遍历a和a.T都是输出一样

In [7]:
for x in np.nditer(a,order='F'):
    print (x, end=", " )
print ('\n')
for x in np.nditer(a.T,order='F'):
    print (x, end=", " )
print ('\n')

0, 3, 1, 4, 2, 5, 

0, 1, 2, 3, 4, 5, 



order='F'是按列优先

In [8]:
for x in np.nditer(a,order='C'):
    print (x, end=", " )
print ('\n')
for x in np.nditer(a.T,order='C'):
    print (x, end=", " )
print ('\n')

0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 



order='C'是按行优先

In [10]:
a = np.arange(10,22)
a = a.reshape(3,4)
print  ('第一个数组为：')
print (a)

print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)
print (b)

print ('修改后的数组为：')
for x,y in np.nditer([a,b]):
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
第二个数组为：
[1 2 3 4]
修改后的数组为：
10:1, 11:2, 12:3, 13:4, 14:1, 15:2, 16:3, 17:4, 18:1, 19:2, 20:3, 21:4, 

上面是广播迭代功能

In [15]:
a = np.arange(10,22)
a = a.reshape(3,4)
print  ('第一个数组为：')
print (a)

print ('第二个数组为：')
b = np.array([[1],  [2],  [3]], dtype =  int)
print (b)

print ('修改后的数组为：')
for x,y in np.nditer([a,b]):
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
第二个数组为：
[[1]
 [2]
 [3]]
修改后的数组为：
10:1, 11:1, 12:1, 13:1, 14:2, 15:2, 16:2, 17:2, 18:3, 19:3, 20:3, 21:3, 

# np.bincount

In [2]:
import numpy as np
x = np.arange(1,7)
i = np.bincount(x)
print(i)

[0 1 1 1 1 1 1]


输出[0 1 1 1 1 1 1]表示，1~6出现的次数为1, np.bincount返回数组的长度为输入x的最大值加1

In [3]:
x = np.arange(1,7)
i = np.random.randint(0,10,6)
f = np.bincount(i,x)
print(x)
print(i)
print(f)

[1 2 3 4 5 6]
[7 5 3 6 1 7]
[0. 5. 0. 3. 0. 2. 4. 7.]


In [ ]:
np.bincount 入参为两个的时候，两个入参list长度必须相同，返回数组长度为第二个入参中最大值加1，
返回的数组每个index的值为第二个数组的对应第一个数组的值的和

# numpy中的...

In [7]:
a = np.arange(2*3*4).reshape(2,3,4)
print(a)
print(a[0,...])
print(a[0,:,:])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


...表示所有维度，a[0,...]表示第一个维度取0，其他取所有维度，

In [9]:
print(a[...,0])

[[ 0  4  8]
 [12 16 20]]


In [21]:
a = np.ones((3,3))
b = a[...,None]
print(a)
print(b)
print(a.shape)
print(b.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
(3, 3)
(3, 3, 1)


可以通过...来表示所有的维度，来增加一个维度

# numpy中的axis

In [17]:
import numpy as np
a = np.arange(24).reshape(2,3,4)
print(a.shape)
print(a.sum(axis=2))
print(a.sum(axis=0))

(2, 3, 4)
[[ 6 22 38]
 [54 70 86]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


a是shape为(2,3,4)的矩阵，axis入参可以是int，也可以是int的tuple， 

In [18]:
print(np.sum(a,axis=(-2,-1)))

[ 66 210]


### 已知A\B\C 点， 求点C距离A与B确定直线的距离

In [23]:
import numpy as np
a = np.random.randint(0,10,(2,1))
b = np.random.randint(0,10,(2,1))
c = np.random.randint(0,10,(2,1))
print(a)
print(b)
print(c)

[[5]
 [2]]
[[0]
 [6]]
[[2]
 [7]]


实现的点p距由点P0和P1确定的直线的距离，如下方法（参考numpy-100（78））

In [7]:
def distance1(P0, P1, p):
    T = P1 - P0
    L = (T ** 2).sum(axis=1)
    t1 = P0 - p
    t2 = -(t1 * T)
    L = L.reshape(len(L), 1)
    U = t2 / L
    U = np.sum(U, axis=1)
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D ** 2).sum(axis=1))

# np.lib.stride_tricks.as_strided

In [17]:
data = np.random.randint(0,10,(5,5))
print(data)

[[0 3 4 8 3]
 [1 6 7 6 1]
 [7 9 2 4 9]
 [6 4 5 0 2]
 [6 4 3 3 0]]


In [19]:
a=np.lib.stride_tricks.as_strided(data,shape=(3,3,3,3),strides=(20,4,20,4))
a

array([[[[0, 3, 4],
         [1, 6, 7],
         [7, 9, 2]],

        [[3, 4, 8],
         [6, 7, 6],
         [9, 2, 4]],

        [[4, 8, 3],
         [7, 6, 1],
         [2, 4, 9]]],


       [[[1, 6, 7],
         [7, 9, 2],
         [6, 4, 5]],

        [[6, 7, 6],
         [9, 2, 4],
         [4, 5, 0]],

        [[7, 6, 1],
         [2, 4, 9],
         [5, 0, 2]]],


       [[[7, 9, 2],
         [6, 4, 5],
         [6, 4, 3]],

        [[9, 2, 4],
         [4, 5, 0],
         [4, 3, 3]],

        [[2, 4, 9],
         [5, 0, 2],
         [3, 3, 0]]]])

shape=(3,3,3,3)比较好理解，就是输出的张量大小，strides=(20,4,20,4)表示每个维度各个元素之间的距离

## strides

In [16]:
a = np.arange(9).reshape(3,3)
print(a[0,0])
print(a.strides)
print(a.dtype)

0
(12, 4)
int32


a.strides为(12, 4), 表示某个维度下，每个元素之间的距离是多少字节，a是二维矩阵，第0维（我这么说）a[0,0]到a[0,1]之间间隔一个元素，a的dtype为int32，为4个字节，因此为4，第一维，两元素之间的距离例如a[0,0]到a[1,0],间隔3个元素，因此为3*4=12

# numpy view

In [26]:
a=np.array([1,2,3,4])
c=a.view()
b=a.reshape(2,2)
print(c is a)
print(c.base is a)
print (np.may_share_memory(a, b))

False
True
True


共享内存

# np.add.reduceat

In [3]:
a = np.arange(9).reshape(3,3)
print(a)
print(np.add.reduce(a))
print(np.add.reduce(a,0))
print(np.add.reduce(a,1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[ 9 12 15]
[ 9 12 15]
[ 3 12 21]


np.add.reduce(a,0)的0是axis的参数值，默认为0， 如果，a.shape=(2,3,4)，np.add.reduce(a,0)得到（3,4),np.add.reduce(a,1)得到（2,4),np.add.reduce(a,2)得到（2,3)

In [4]:
a =np.arange(9)
b =np.add.reduceat(a,[0,4,1,5])
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[ 6  4 10 26]


[ 6  4 10 26]是6是0-4的和，10是1-5的和，6和10后的值4和26，如果不是最后一个，就是index的值（4），如果是最后一个，就是从index（5）到最后的和(5+6+7+8)

In [36]:
a =np.arange(9)
b =np.add.reduceat(a,np.arange(0,9,3))
print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[ 3 12 21]


In [ ]:
0+1+2=3,3+4+5=12,6+7+8=21， 入参indices，的长度是奇数与偶数，返回的结果是不同的

# np.ceil

In [2]:
import numpy as np
a = np.random.uniform(-10,10,10)
print(a)
print(np.ceil(a))

[-0.41875273  4.33634524  4.52020078  6.9540971   9.31027603  2.60645365
  7.40756695  0.35796198 -4.62597617 -7.77386655]
[-0.  5.  5.  7. 10.  3.  8.  1. -4. -7.]


返回比该数大的最近的整数

# np.pad

# （5，3）减（5，）

In [14]:
a = np.random.randint(0,10,(5,3))
b=np.random.randint(0,10,5)
print(a.shape)
print(b.shape)
np.subtract(a,b)

(5, 3)
(5,)


ValueError: operands could not be broadcast together with shapes (5,3) (5,) 

直接减，提示失败，要把b转成（5，1），然后再减

In [13]:
b=b.reshape(-1,1)
print(b.shape)
print(a-b)

(5, 1)
[[ 0 -4 -1]
 [ 1 -5  1]
 [-8 -8 -4]
 [-3  4 -4]
 [-1 -5  2]]


In [15]:
c=np.random.random((5,3))
d=np.random.random(3)
c-d

array([[0.71716732, 0.21879721, 0.29707115],
       [0.50162136, 0.17568624, 0.15386987],
       [0.39055754, 0.42969877, 0.12366557],
       [0.40176057, 0.60288569, 0.1546302 ],
       [0.73802933, 0.10498121, 0.39020554]])

(5,3)减(3,)就是可以的

# np.concatenate

In [ ]:
将多个numpy数组合并成一个

In [3]:
a=np.arange(0,4).reshape(2,2)
b=np.arange(4,8).reshape(2,2)
print(np.concatenate((a,b)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [ ]:
print(np.concatenate([a,b)))