# StandardScaler

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
np.random.seed(123)
print('use sklearn')
# 注：shape of data: [n_samples, n_features]
data = np.random.randn(10, 4)
print(data)
scaler = StandardScaler()
scaler.fit(data)
trans_data = scaler.transform(data)
print(trans_data)

use sklearn
[[-1.0856306   0.99734545  0.2829785  -1.50629471]
 [-0.57860025  1.65143654 -2.42667924 -0.42891263]
 [ 1.26593626 -0.8667404  -0.67888615 -0.09470897]
 [ 1.49138963 -0.638902   -0.44398196 -0.43435128]
 [ 2.20593008  2.18678609  1.0040539   0.3861864 ]
 [ 0.73736858  1.49073203 -0.93583387  1.17582904]
 [-1.25388067 -0.6377515   0.9071052  -1.4286807 ]
 [-0.14006872 -0.8617549  -0.25561937 -2.79858911]
 [-1.7715331  -0.69987723  0.92746243 -0.17363568]
 [ 0.00284592  0.68822271 -0.87953634  0.28362732]]
[[-0.94511643  0.58665507  0.5223171  -0.93064483]
 [-0.53659117  1.16247784 -2.13366794  0.06768082]
 [ 0.9495916  -1.05437488 -0.42049501  0.3773612 ]
 [ 1.13124423 -0.85379954 -0.19024378  0.06264126]
 [ 1.70696485  1.63376764  1.22910949  0.8229693 ]
 [ 0.52371324  1.02100318 -0.67235312  1.55466934]
 [-1.08067913 -0.85278672  1.13408114 -0.858726  ]
 [-0.18325687 -1.04998594 -0.00561227 -2.1281129 ]
 [-1.49776284 -0.9074785   1.15403514  0.30422599]
 [-0.06810748  0.3

输出均值和方差，通过numpy的方法也可以获取均值和方差

In [6]:
print(scaler.mean_)
print(scaler.var_)

[ 0.08737571  0.33094968 -0.24989369 -0.50195303]
[1.54038781 1.29032409 1.04082479 1.16464894]


In [7]:
print(data.mean(axis=0))
print(data.var(axis=0))

[ 0.08737571  0.33094968 -0.24989369 -0.50195303]
[1.54038781 1.29032409 1.04082479 1.16464894]


In [4]:
print(scaler.transform(data))

[[-0.94511643  0.58665507  0.5223171  -0.93064483]
 [-0.53659117  1.16247784 -2.13366794  0.06768082]
 [ 0.9495916  -1.05437488 -0.42049501  0.3773612 ]
 [ 1.13124423 -0.85379954 -0.19024378  0.06264126]
 [ 1.70696485  1.63376764  1.22910949  0.8229693 ]
 [ 0.52371324  1.02100318 -0.67235312  1.55466934]
 [-1.08067913 -0.85278672  1.13408114 -0.858726  ]
 [-0.18325687 -1.04998594 -0.00561227 -2.1281129 ]
 [-1.49776284 -0.9074785   1.15403514  0.30422599]
 [-0.06810748  0.31452186 -0.61717074  0.72793583]]


通过scaler.transform得到的标准化数据，其实和下面的方法一样

In [4]:
(data-scaler.mean_)/np.sqrt(scaler.var_)

array([[-0.94511643,  0.58665507,  0.5223171 , -0.93064483],
       [-0.53659117,  1.16247784, -2.13366794,  0.06768082],
       [ 0.9495916 , -1.05437488, -0.42049501,  0.3773612 ],
       [ 1.13124423, -0.85379954, -0.19024378,  0.06264126],
       [ 1.70696485,  1.63376764,  1.22910949,  0.8229693 ],
       [ 0.52371324,  1.02100318, -0.67235312,  1.55466934],
       [-1.08067913, -0.85278672,  1.13408114, -0.858726  ],
       [-0.18325687, -1.04998594, -0.00561227, -2.1281129 ],
       [-1.49776284, -0.9074785 ,  1.15403514,  0.30422599],
       [-0.06810748,  0.31452186, -0.61717074,  0.72793583]])

通过numpy运算也可以

In [10]:
(data-np.mean(data,axis=0))/np.std(data,axis=0)

array([[-0.94511643,  0.58665507,  0.5223171 , -0.93064483],
       [-0.53659117,  1.16247784, -2.13366794,  0.06768082],
       [ 0.9495916 , -1.05437488, -0.42049501,  0.3773612 ],
       [ 1.13124423, -0.85379954, -0.19024378,  0.06264126],
       [ 1.70696485,  1.63376764,  1.22910949,  0.8229693 ],
       [ 0.52371324,  1.02100318, -0.67235312,  1.55466934],
       [-1.08067913, -0.85278672,  1.13408114, -0.858726  ],
       [-0.18325687, -1.04998594, -0.00561227, -2.1281129 ],
       [-1.49776284, -0.9074785 ,  1.15403514,  0.30422599],
       [-0.06810748,  0.31452186, -0.61717074,  0.72793583]])

# LinearRegression

In [4]:
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3
reg = LinearRegression().fit(X, y)
print(reg.score(X, y))

print(reg.coef_)

print(reg.intercept_)

print(reg.predict(np.array([[3, 5]])))

1.0
[1. 2.]
3.0000000000000018
[16.]


In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
X, y = make_regression(n_samples=1000, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
lr = LinearRegression()
lr.fit(X_train, y_train)
print(lr.score(X_test, y_test))

1.0


# StandardScaler

In [2]:
from sklearn.preprocessing import StandardScaler
data = [[0, 0], [0, 0], [1, 1], [1, 1]]
scaler = StandardScaler()
print(scaler.fit(data))
print(scaler.transform(data))

StandardScaler(copy=True, with_mean=True, with_std=True)
[[-1. -1.]
 [-1. -1.]
 [ 1.  1.]
 [ 1.  1.]]


In [ ]:
print(scaler.mean_)
print(scaler.var_)

In [ ]:
期望和标准差，可以通过numpy的mean和var方法获取,scaler.transform获取标准化数据，如果自己计算，为(data-scaler.mean_)/np.sqrt(scaler.var_)